id: fs-demo
namespace: io.priam.berkan

tasks:
  - id: demo-fs
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - /usr/local/bin/python3.10 /production/etl/tests/test_fortisiem.py
    runner: DOCKER
    dockerOptions:
      pullPolicy: ALWAYS
      dockerConfig: |
        {
          "auths": {
            "https://index.docker.io/v1/": {
              "auth":  "{{ secret('DOCKER_AUTH_TOKEN') | base64encode }}"
            }
          }
        }
      image: priamai/etl-demo:latest
      networkMode: ava_network
    env:
      CTS_URL: http://avaweb_backend:8080/api/
      ML_URL: http://avapi:8070
      REDIS_HOST: redis
triggers:
  - id: hourly
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@hourly"
    stopAfter:
      - FAILED
